# Generated by Django 2.2.4 on 2019-08-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='language',
            field=models.CharField(help_text="Enter the book's primary language", max_length=100),
        ),
    ]
